version: '3.8'

services:
  backend-server:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    container_name: backend-server
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./database
    ports:
      - "27017:27017"
    container_name: mongo